/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Cell } from "./components/spreadsheet/types";
export { Cell } from "./components/spreadsheet/types";
export namespace Components {
    interface AppCell {
        "cell": Cell;
        "col": number;
        /**
          * @default false
         */
        "isInRange": boolean;
        /**
          * @default false
         */
        "isSelected": boolean;
        "row": number;
    }
    interface AppSpreadsheet {
    }
}
export interface AppCellCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppCellElement;
}
declare global {
    interface HTMLAppCellElementEventMap {
        "cellValueChanged": { row: number; col: number; value: string };
        "cellSelected": { row: number; col: number };
    }
    interface HTMLAppCellElement extends Components.AppCell, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppCellElementEventMap>(type: K, listener: (this: HTMLAppCellElement, ev: AppCellCustomEvent<HTMLAppCellElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppCellElementEventMap>(type: K, listener: (this: HTMLAppCellElement, ev: AppCellCustomEvent<HTMLAppCellElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppCellElement: {
        prototype: HTMLAppCellElement;
        new (): HTMLAppCellElement;
    };
    interface HTMLAppSpreadsheetElement extends Components.AppSpreadsheet, HTMLStencilElement {
    }
    var HTMLAppSpreadsheetElement: {
        prototype: HTMLAppSpreadsheetElement;
        new (): HTMLAppSpreadsheetElement;
    };
    interface HTMLElementTagNameMap {
        "app-cell": HTMLAppCellElement;
        "app-spreadsheet": HTMLAppSpreadsheetElement;
    }
}
declare namespace LocalJSX {
    interface AppCell {
        "cell": Cell;
        "col": number;
        /**
          * @default false
         */
        "isInRange"?: boolean;
        /**
          * @default false
         */
        "isSelected"?: boolean;
        "onCellSelected"?: (event: AppCellCustomEvent<{ row: number; col: number }>) => void;
        "onCellValueChanged"?: (event: AppCellCustomEvent<{ row: number; col: number; value: string }>) => void;
        "row": number;
    }
    interface AppSpreadsheet {
    }
    interface IntrinsicElements {
        "app-cell": AppCell;
        "app-spreadsheet": AppSpreadsheet;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-cell": LocalJSX.AppCell & JSXBase.HTMLAttributes<HTMLAppCellElement>;
            "app-spreadsheet": LocalJSX.AppSpreadsheet & JSXBase.HTMLAttributes<HTMLAppSpreadsheetElement>;
        }
    }
}
